### ISSUE TITLE
Include the property listing *before* the method details

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp-api-docs#47]
Move the property summary after the method summary but before the method details. This will help people who are trying to scan the property list without reading the full method docs.

**Comment by chinpei215** [comment]
Can we have four tables?

1. The property summary
2. The method summary (https://developers.google.com/apps-script/reference/spreadsheet/spreadsheet#methods)
3. The property details
4. The method details (https://developers.google.com/apps-script/reference/spreadsheet/spreadsheet#detailed-documentation)

**Comment by markstory** [comment]
Most properties don't have much in the way of details. Are you thinking that the property summary would be just one line of text?

**Comment by chinpei215** [comment]
> Are you thinking that the property summary would be just one line of text?

Yes, I am.

We might have several additional information in the property details - Accesibility, Default value, Since, and See also, like a java reference. 
https://docs.oracle.com/javase/8/javafx/api/javafx/scene/web/WebView.html#property.summary
But the properties detail might not be required, if we have a readable properties summary.

And I forgot about constants. The constants summary looks pretty readable to me.
http://api.cakephp.org/3.2/class-Cake.ORM.Table.html#constants

**Comment by markstory** [comment]
Our current property details [includes default values](http://api.cakephp.org/3.2/class-Cake.Cache.Engine.ApcEngine.html#$_config). I'll draft up a properties summary this weekend and post screen shots.

**Comment by chinpei215** [comment]
OK. Thank you always.

**Comment by markstory** [comment]
Pull request up now.
