### ISSUE TITLE
Moving away from ApiGen?

### ISSUE THREAD

**Issue by ravage84** [cakephp/cakephp-api-docs#99]
As discussed in the dev channel :

- [CakePHP uses ApiGen for generating its API documentations](https://github.com/cakephp/cakephp-api-docs/blob/master/composer.json#L6) for years now
- ApiGen 4.x is not compatible with PHP 7.0+, usage of PHP 7 language features leads to "Unknown Token found." error
- [ApiGen 5.x is not yet released](https://github.com/ApiGen/ApiGen/tree/8141881dc8032fcfbf0a63f8f3e4dce69e566e7e#your-help-is-needed-to-finish-5x-release), [current release candidate seems to be a mess](https://github.com/ApiGen/ApiGen/issues/1015) and general progress  seems very slow
- CakePHP 4.0 will have a minimum PHP compatibility of 7+, so the current ApiGen will not work for us anymore

This means once we start working on CakePHP 4.0 we will not be able to generate API documentation anymore.

What are our options:

- Wait for ApiGen 5.0 to be released (may be help 'em)
- Moving away from ApiGen as our API docs generator

What alternatives are there?

- [phpDocumentor2](https://github.com/phpDocumentor/phpDocumentor2), the classic
- [FriendsOfPHP SAMI](https://github.com/FriendsOfPHP/Sami), used by Symfony & Laravel
- [calinrada/php-apidoc](https://github.com/calinrada/php-apidoc)
- others?

**Comment by markstory** [comment]
I'm no longer confident in ApiGen and its future. I am for moving off when we're required to. Sami seems to be simple enough to get running and has search which is a requirement. It also good templating support.

**Comment by ADmad** [comment]
Sami :+1+

**Comment by enumag** [comment]
From my experience Sami generated API docs is completely useless. Symfony API documentation never ever helped me where as any ApiGen based documentation is great. The main reasons why Sami is useless are:

1. When you open an interface it doesn't show you what classes implement it.
2. It can't show the source code.

**Comment by ravage84** [comment]
As much as I would prefer to stay with ApiGen, its past development history didn't give us much trust in it's near to middle future.

**Comment by jeremyharris** [comment]
> It can't show the source code.

This is also a concern of mine. I often peek into the source while browsing the docs, and use it as a reference when in #support. I found myself very frustrated browsing Symfony docs looking for links to the source. Not sure if Sami can be extended to support at least linking to source.

**Comment by markstory** [comment]
Looks like adding links to source [has been attempted at least once](https://github.com/FriendsOfPHP/Sami/pull/64/files) before in sami. I'm not able to figure out if it is a current feature from a 30 second reading of their docs.

**Comment by jeremyharris** [comment]
@markstory following the thread, it looks like it was [integrated here][1]. And Laravel apparently has it set up, so we can integrate view source also.

Sami is looking like a better option now.

[1]: https://github.com/FriendsOfPHP/Sami/pull/91

**Comment by ADmad** [comment]
Not probably a deal breaker but Sami doesn't seem to have ability to list deprecations like ApiGen does.

**Comment by TomasVotruba** [comment]
As @apigen former long time maintainer, it'd need to version 5 to be finished. 

I don't maintain the project anymore, cause I don't believe in it's purpose. It's better, faster, easier to use now to download package with composer, open in PHPStorm and just explore, rather than look at some poorly linked HTML tries to mimic who-know which version.

Saying that, last year I moved Apigen from custom unmtaintained, PHP 5.5+ broken Reflection to [BetterReflectoin](https://www.tomasvotruba.cz/blog/2017/09/04/how-apigen-survived-its-own-death/). Then it stepped down, moving the project with v5.0.0-RC5 to another maintainer. Unfortunately, he didn't find time for release every since.

To conclude, I'd delete the api and recommend PHPStorm approach. But if you really incist, before migrating to completelly different doc generator, I'd give the v5.0.0-RC5 a try (at least for 1-2 hours). It has many new features and PHP 7.2 support right away (guys from BetterReflectoin are doing great job and I belive it's state of art for the reflection in PHP nowadays).

If that still doesn't give you the feeling it's the right tool you, feel free to migrate to another one.

**Comment by markstory** [comment]
@TomasVotruba Thanks for all the great work on ApiGen in the past. I don't think deleting our API docs is a realistic solution. While PHPStorm works for you, there are tons of folks who use other tools and prefer HTML based API docs. Giving he 5.0.0-RC5 release a shot is something we can try before moving to another tool.

**Comment by jtraulle** [comment]
Hey, hello there :wave: 

Any progress on this ?

Have you tried Doxygen as an alternative ? 

https://fossies.org/dox/cakephp-4.0.2/ is a good example of what can be obtained.

Really like the diagrams generated by Doxygen.

**Comment by stork** [comment]
> there are tons of folks who use other tools and prefer HTML based API docs.

Exactly. I am heavily using https://devdocs.io/ for all kind of api docs, moving away from ApiGen will require update of their scraper.

**Comment by othercorey** [comment]
We have a solution in-progress.

**Comment by othercorey** [comment]
Closing as we have an in-house solution for api docs now.
